### ISSUE TITLE
TED5000/6000 Rate Value

### ISSUE THREAD

**Issue by realumhelp** [rianadon/the-energy-detective-py#11]
It looks like Home Assistant can pull either an entity for Current Price and/or Total Cost. Current price seems straight forward but, I don't fully understand what Total Cost means in HA terms, my guess is total month to date cost.

My guess at the proper queries to pull data from:
```
Current Price - The current price of electricity at this time.
 * TED5000:
   * LiveData.xml["LiveData"]["Utility"]["CurrentRate"] / 100000 - The current rate in effect
 * TED6000:
   * Rate.xml["Rate"]["Value"] / 100000 - Current Rate in effect
```
```
Total Cost - I'm not exactly sure what exactly this value means. I'd assume total monthly cost?
 * TED5000:
   * LiveData.xml["LiveData"]["Cost"]["Total"]["CostMTD"] / 100 - Cumulative Cost since the beginning of the billing
cycle
 * TED6000:
   * DashData.xml?T=1&D=0&M=0["DashData"]["MTD"] / 100 - The cumulative readings since the beginning of the billing cycle
```

**Comment by rianadon** [comment]
Home Assistant should be able to match the cost-tracking capabilities of the meter using the [utility_meter](https://www.home-assistant.io/integrations/utility_meter/) integration (and perhaps be able to support even more types of energy plans), so while I appreciate the research I would like to limit functionality to retrieving only energy usage.

**Comment by realumhelp** [comment]
No problem. I just saw the ability to set entities for those fields in HA and saw that TED can supply those values. I actually spent a good amount of time entering my energy bill info into TED to get it reasonably accurate at one time. I've never used the energy tracking stuff in HA yet so I'm not sure what all it can do. It seems cool so I'm excited to give it a try.
