### ISSUE TITLE
Add MTU Daily and Monthly Data

### ISSUE THREAD

**Issue by realumhelp** [rianadon/the-energy-detective-py#5]
This information is available in the LiveData.xml for TED5000 and available with a DashData query DashData.xml?T=0&D=255&M=${MTU_NUMBER}

T -> 0 = Power, 1 = Cost
D -> 0 = NET, 1 = LOAD, 2 = GEN, 255 = MTU
M -> [0-4] MTU Index. Only used if D = 255

The interface isn't super clear as to what LOAD and GEN mean for the DashData query. I THINK that NET is LOAD + GEN, LOAD is LOAD totals, and GEN is GEN totals, but not 100%. Probably better to only use the NET and MTU values.

**Comment by rianadon** [comment]
It's great to know we have access to load/gen/mtu totals! I think as a first pass using just NET and MTU is fine, but it would be nice to do load vs gen breakdowns as well!

**Comment by realumhelp** [comment]
The queries would be:

```
http://{}/api/DashData.xml?T=0&D=1&M=0
http://{}/api/DashData.xml?T=0&D=2&M=0
```

My system returns all 0's for the data when I run them. I think that they only matter for System Type 1 and 2: (NET + GEN and/or NET + LOAD)
